### ISSUE TITLE
Searching for '\' within a string mapper

### ISSUE THREAD

**Issue by nlacey** [Stratio/cassandra-lucene-index#236] opened 2016-11-14 18:15 UTC
If I add data to a lucene map[text]text with a string map
//Search
Create table search (
    time_bucket    Text,
    search_string  map<Text,Text>,
    lucene         Text,
    Primary Key ( time_bucket )
) ;

DROP INDEX IF EXISTS search_unittest41044_search_index;
CREATE CUSTOM INDEX search_unittest41044_search_index ON search(lucene)
USING 'com.stratio.cassandra.lucene.Index'
WITH OPTIONS = {
    'refresh_seconds': '1',
    'schema': '{
        fields : {
            search_string:  {type : "string", case_sensitive: false},
           }
    }'
};

```
Add  data to the map that contains  '\'
cqlsh shows
'user': 'nova\billyjohnson'

I have to add 4 '\' in order to get the record back
select search_string from  search where lucene = '{"filter":{"type":"boolean","must":[{"type":"wildcard","field":"search_string$user","value":"nova\\\\billyjohn*"}]}}';
```

**Comment by ealonsodb** [comment] 2016-11-15 09:13
Hi @nlacey:

Remeber
```
select search_string from search where lucene = '{
    "filter":{"type":"boolean","must":
        [
            {"type":"wildcard","field":"search_string$user","value":"nova\\billyjohn*"}
        ]
    }
}';
```
is just the same as: 
```
select search_string from search where lucene = '{
    "filter":{"type":"wildcard","field":"search_string$user","value":"nova\\billyjohn*"}
}';
```

Actually, what is your question?

**Comment by nlacey** [comment] 2016-11-15 12:35
```
Sorry github was displaying my post funny, I edited above (now shown correctly in grey)

if you insert data as nova\\billyjohnson (golang)

it will show up in cqlsh as 'user': 'nova\billyjohnson'

but if you want to search for it in lucene, you'll need to double escape each '\'
select search_string from  search where lucene = '{"filter":{"type":"boolean","must":[{"type":"wildcard","field":"search_string$user","value":"nova\\\\billyjohn*"}]}}';
```

**Comment by ealonsodb** [comment] 2016-11-15 14:47
Hi @nlacey 

Yes, the problem is that '\' is an special character both in String and lucene [queryparser](https://lucene.apache.org/core/5_5_1/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#Escaping_Special_Characters)
So, "nova\\\\billyjohn*" parsed by String as: "nova\\billyjohn*" and lucene do it again. 

So, basicly, you need 4 '\' to query it or dont use this special characters. 

If you want to be sure about this try uinserting the same data with '/' instead of '\' and you will only need to espace it once: 

```
SELECT search_string FROM  search WHERE lucene = '{
    "filter":{"type":"boolean","must":
        [
            {"type":"wildcard","field":"search_string$user","value":"nova\/billyjohn*"}
        ]
    }
}';
```

Cheers

**Comment by adelapena** [comment] 2016-11-23 16:15
This is the expected behaviour of escaping special character in nested syntaxes. I'm closing the issue, we can reopen it if there is some alternative approach to solve the ambiguity.

**Closed by adelapena** 2016-11-23 16:15 UTC
