### ISSUE TITLE
What I'm guessing are old deleted rows showing up in query, but not filter

### ISSUE THREAD

**Issue by ayurkows** [Stratio/cassandra-lucene-index#106] opened 2016-03-11 16:23 UTC
cqlsh> SELECT id, username FROM Story.users;

 id                                   | username
--------------------------------------+----------
 23a81d41-a9e3-420c-a9cf-46623d887361 |   frnds0
 0b375014-ebf1-47a9-af88-b860feedaf0d |   frnds6
 794f0ef4-4bd1-4fb3-9734-561bfff74074 |  frnds16
 9b3f5326-9a58-482a-8b1b-bb177e79f35f |  frnds11
 feed474e-d7e0-4a36-afae-15735c7afe3f |     alex
 a2c10b20-d2cb-4eed-9c26-94bdb6eefb2e |  frnds25
 e666ba23-91aa-4f68-84bf-46115b2dd8ac |  frnds23
 b3a475b4-67b3-46c2-a7e2-59043217be69 |   frnds8
 d14b5ce2-15fe-4879-a131-360b1d6092b6 |  frnds21
 2976c6ec-69c8-4a05-b885-50c585c9eaa9 |    alex2
 8e83215a-4ffc-46e2-9c36-5fdb50b4007b |  frnds17
 1d2add9f-dfda-4a4f-b84d-a7e06fa79647 |  frnds15
 52256d0b-4c8d-4acf-b9c9-908515e8f4fc |  frnds24
 a3996aec-ce15-4bc2-a928-64d81e956788 |  frnds10
 04af4736-ab7a-44f7-9de2-064dd7a19f00 |   frnds7
 fb5aa463-70c3-46b2-825c-fd745165d3a3 |   frnds5
 3b7b6fdc-83db-4430-befe-fd6141a31c56 |  frnds27
 85518358-9e4a-40e0-8aa8-7928f104bdb7 |  frnds18
 dde13eae-321a-4e02-ab5d-94512ac45986 |   frnds2
 b3400bf5-354d-4768-bc9f-8cb0293be540 |   frnds9
 3e476519-bda6-4897-b5db-0c884b4be5e6 |  frnds29
 9942c92d-f195-45a4-aa35-bee40fddc36a |  frnds26
 fc1d289e-3836-44ef-a2cd-9a3047b02740 |   frnds3
 be34de28-22aa-4d68-b205-5421fbd5ed66 |  frnds13
 f7b30860-033a-498e-80e0-a99a794fc7d1 |  frnds22
 4c41660e-1094-4949-a5df-f4abf2c30eaf |  frnds28
 11ed2dbe-f037-4e24-ab77-168b31308bd1 |  frnds20
 23e63926-ed71-4420-878c-9ce6239fecc7 |   frnds1
 8237d415-5048-406c-a0c8-2175ea3d2678 |   frnds4
 8f11f3e3-2e12-4495-865e-2e637749ef5a |  frnds12
 59ef5c50-4ec6-42de-82bd-170eaf153895 |  frnds19
 85e8bfb0-f9b9-4f30-8bda-b25cab21e58d |  frnds14

(32 rows)
cqlsh> SELECT id, username FROM story.users WHERE lucene = '{filter: {type: "range", field: "id", lower: "9b3f5326-9a58-482a-8b1b-bb177e79f35f"},sort: {fields: [ {field:"id", reverse:false}, {field:"id", reverse:false} ] }}';

 id                                   | username
--------------------------------------+----------
 a2c10b20-d2cb-4eed-9c26-94bdb6eefb2e |  frnds25
 a3996aec-ce15-4bc2-a928-64d81e956788 |  frnds10
 b3400bf5-354d-4768-bc9f-8cb0293be540 |   frnds9
 b3a475b4-67b3-46c2-a7e2-59043217be69 |   frnds8
 be34de28-22aa-4d68-b205-5421fbd5ed66 |  frnds13
 d14b5ce2-15fe-4879-a131-360b1d6092b6 |  frnds21
 dde13eae-321a-4e02-ab5d-94512ac45986 |   frnds2
 e666ba23-91aa-4f68-84bf-46115b2dd8ac |  frnds23
 f7b30860-033a-498e-80e0-a99a794fc7d1 |  frnds22
 fb5aa463-70c3-46b2-825c-fd745165d3a3 |   frnds5
 fc1d289e-3836-44ef-a2cd-9a3047b02740 |   frnds3
 feed474e-d7e0-4a36-afae-15735c7afe3f |     alex

(12 rows)

cqlsh> SELECT id, username FROM story.users WHERE lucene = '{query: {type: "range", field: "id", lower: "9b3f5326-9a58-482a-8b1b-bb177e79f35f"},sort: {fields: [ {field:"id", reverse:false}, {field:"id", reverse:false} ] }}';

 id                                   | username
--------------------------------------+----------
 a2c10b20-d2cb-4eed-9c26-94bdb6eefb2e |  frnds25
 a3996aec-ce15-4bc2-a928-64d81e956788 |  frnds10
 ac5ef240-70b9-4615-9744-b2274a605fc0 |     null
 b3400bf5-354d-4768-bc9f-8cb0293be540 |   frnds9
 b3a475b4-67b3-46c2-a7e2-59043217be69 |   frnds8
 be34de28-22aa-4d68-b205-5421fbd5ed66 |  frnds13
 c4f7d039-3328-4ebd-afb8-8b547446ca89 |     null
 d14b5ce2-15fe-4879-a131-360b1d6092b6 |  frnds21
 dde13eae-321a-4e02-ab5d-94512ac45986 |   frnds2
 e666ba23-91aa-4f68-84bf-46115b2dd8ac |  frnds23
 f3e506eb-9644-4fd2-bd03-3a6db6cad504 |     null
 f7b30860-033a-498e-80e0-a99a794fc7d1 |  frnds22
 fb5aa463-70c3-46b2-825c-fd745165d3a3 |   frnds5
 fc1d289e-3836-44ef-a2cd-9a3047b02740 |   frnds3
 fcce7964-0016-435e-837a-2ebc6416bb89 |     null
 feed474e-d7e0-4a36-afae-15735c7afe3f |     alex

(16 rows)

The rows with a null username shouldn't exist?

**Comment by adelapena** [comment] 2016-03-11 20:00
Which version of Apache Cassandra and which version of the Lucene index plugin are you using? Could you please paste here both the table and the index creation statements?

**Comment by ayurkows** [comment] 2016-03-14 13:02
Apache cassandra 2.2.4
Lucene index plugin 2.2.4.4

"CREATE TABLE IF NOT EXISTS story.users(id uuid, username text, lucene text, PRIMARY KEY(id))"

"CREATE CUSTOM INDEX IF NOT EXISTS users_idx ON story.users(lucene) USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {'refresh_seconds':'1', 'schema':'{fields : {id: {type: \"uuid\", sorted: true}, username: {type: \"text\", sorted: true}}}'}"

**Comment by adelapena** [comment] 2016-03-14 14:34
I can't reproduce the issue.

I create the schema this way, using a 3 node CCM cluster:
```
CREATE KEYSPACE story WITH REPLICATION = {'class' : 'SimpleStrategy',  'replication_factor': 3};

CREATE TABLE IF NOT EXISTS story.users(id uuid, username text, lucene text, PRIMARY KEY(id));

CREATE CUSTOM INDEX IF NOT EXISTS users_idx ON story.users(lucene) 
USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = 
{'refresh_seconds':'1', 
 'schema':'{fields : 
 	{id: {type: "uuid", sorted: true}, 
 	username: {type: "text", sorted: true}}}'
};
```

Then I insert the dataset inferred from your SELECT results, and the rows to be deleted:
```
INSERT INTO story.users (id, username ) VALUES (23a81d41-a9e3-420c-a9cf-46623d887361, 'frnds0');
INSERT INTO story.users (id, username ) VALUES (0b375014-ebf1-47a9-af88-b860feedaf0d, 'frnds6');
INSERT INTO story.users (id, username ) VALUES (794f0ef4-4bd1-4fb3-9734-561bfff74074, 'frnds16');
INSERT INTO story.users (id, username ) VALUES (9b3f5326-9a58-482a-8b1b-bb177e79f35f, 'frnds11');
INSERT INTO story.users (id, username ) VALUES (feed474e-d7e0-4a36-afae-15735c7afe3f, 'alex');
INSERT INTO story.users (id, username ) VALUES (a2c10b20-d2cb-4eed-9c26-94bdb6eefb2e, 'frnds25');
INSERT INTO story.users (id, username ) VALUES (e666ba23-91aa-4f68-84bf-46115b2dd8ac, 'frnds23');
INSERT INTO story.users (id, username ) VALUES (b3a475b4-67b3-46c2-a7e2-59043217be69, 'frnds8');
INSERT INTO story.users (id, username ) VALUES (d14b5ce2-15fe-4879-a131-360b1d6092b6, 'frnds21');
INSERT INTO story.users (id, username ) VALUES (2976c6ec-69c8-4a05-b885-50c585c9eaa9, 'alex2');
INSERT INTO story.users (id, username ) VALUES (8e83215a-4ffc-46e2-9c36-5fdb50b4007b, 'frnds17');
INSERT INTO story.users (id, username ) VALUES (1d2add9f-dfda-4a4f-b84d-a7e06fa79647, 'frnds15');
INSERT INTO story.users (id, username ) VALUES (52256d0b-4c8d-4acf-b9c9-908515e8f4fc, 'frnds24');
INSERT INTO story.users (id, username ) VALUES (a3996aec-ce15-4bc2-a928-64d81e956788, 'frnds10');
INSERT INTO story.users (id, username ) VALUES (04af4736-ab7a-44f7-9de2-064dd7a19f00, 'frnds7');
INSERT INTO story.users (id, username ) VALUES (fb5aa463-70c3-46b2-825c-fd745165d3a3, 'frnds5');
INSERT INTO story.users (id, username ) VALUES (3b7b6fdc-83db-4430-befe-fd6141a31c56, 'frnds27');
INSERT INTO story.users (id, username ) VALUES (85518358-9e4a-40e0-8aa8-7928f104bdb7, 'frnds18');
INSERT INTO story.users (id, username ) VALUES (dde13eae-321a-4e02-ab5d-94512ac45986, 'frnds2');
INSERT INTO story.users (id, username ) VALUES (b3400bf5-354d-4768-bc9f-8cb0293be540, 'frnds9');
INSERT INTO story.users (id, username ) VALUES (3e476519-bda6-4897-b5db-0c884b4be5e6, 'frnds29');
INSERT INTO story.users (id, username ) VALUES (9942c92d-f195-45a4-aa35-bee40fddc36a, 'frnds26');
INSERT INTO story.users (id, username ) VALUES (fc1d289e-3836-44ef-a2cd-9a3047b02740, 'frnds3');
INSERT INTO story.users (id, username ) VALUES (be34de28-22aa-4d68-b205-5421fbd5ed66, 'frnds13');
INSERT INTO story.users (id, username ) VALUES (f7b30860-033a-498e-80e0-a99a794fc7d1, 'frnds22');
INSERT INTO story.users (id, username ) VALUES (4c41660e-1094-4949-a5df-f4abf2c30eaf, 'frnds28');
INSERT INTO story.users (id, username ) VALUES (11ed2dbe-f037-4e24-ab77-168b31308bd1, 'frnds20');
INSERT INTO story.users (id, username ) VALUES (23e63926-ed71-4420-878c-9ce6239fecc7, 'frnds1');
INSERT INTO story.users (id, username ) VALUES (8237d415-5048-406c-a0c8-2175ea3d2678, 'frnds4');
INSERT INTO story.users (id, username ) VALUES (8f11f3e3-2e12-4495-865e-2e637749ef5a, 'frnds12');
INSERT INTO story.users (id, username ) VALUES (59ef5c50-4ec6-42de-82bd-170eaf153895, 'frnds19');
INSERT INTO story.users (id, username ) VALUES (85e8bfb0-f9b9-4f30-8bda-b25cab21e58d, 'frnds14');
INSERT INTO story.users (id, username ) VALUES (ac5ef240-70b9-4615-9744-b2274a605fc0, 'to_delete');
INSERT INTO story.users (id, username ) VALUES (c4f7d039-3328-4ebd-afb8-8b547446ca89, 'to_delete');
INSERT INTO story.users (id, username ) VALUES (f3e506eb-9644-4fd2-bd03-3a6db6cad504, 'to_delete');
INSERT INTO story.users (id, username ) VALUES (fcce7964-0016-435e-837a-2ebc6416bb89, 'to_delete');
```
Then I run the filtering search:
```
SELECT id, username FROM story.users WHERE lucene = '{filter: {type: "range", field: "id", lower: "9b3f5326-9a58-482a-8b1b-bb177e79f35f"},sort: {fields: [ {field:"id", reverse:false}, {field:"id", reverse:false} ] }}';

 id                                   | username
--------------------------------------+-----------
 a2c10b20-d2cb-4eed-9c26-94bdb6eefb2e |   frnds25
 a3996aec-ce15-4bc2-a928-64d81e956788 |   frnds10
 ac5ef240-70b9-4615-9744-b2274a605fc0 | to_delete
 b3400bf5-354d-4768-bc9f-8cb0293be540 |    frnds9
 b3a475b4-67b3-46c2-a7e2-59043217be69 |    frnds8
 be34de28-22aa-4d68-b205-5421fbd5ed66 |   frnds13
 c4f7d039-3328-4ebd-afb8-8b547446ca89 | to_delete
 d14b5ce2-15fe-4879-a131-360b1d6092b6 |   frnds21
 dde13eae-321a-4e02-ab5d-94512ac45986 |    frnds2
 e666ba23-91aa-4f68-84bf-46115b2dd8ac |   frnds23
 f3e506eb-9644-4fd2-bd03-3a6db6cad504 | to_delete
 f7b30860-033a-498e-80e0-a99a794fc7d1 |   frnds22
 fb5aa463-70c3-46b2-825c-fd745165d3a3 |    frnds5
 fc1d289e-3836-44ef-a2cd-9a3047b02740 |    frnds3
 fcce7964-0016-435e-837a-2ebc6416bb89 | to_delete
 feed474e-d7e0-4a36-afae-15735c7afe3f |      alex
```
I get the same results for the query:
```
SELECT id, username FROM story.users WHERE lucene = '{query: {type: "range", field: "id", lower: "9b3f5326-9a58-482a-8b1b-bb177e79f35f"},sort: {fields: [ {field:"id", reverse:false}, {field:"id", reverse:false} ] }}';

 id                                   | username
--------------------------------------+-----------
 a2c10b20-d2cb-4eed-9c26-94bdb6eefb2e |   frnds25
 a3996aec-ce15-4bc2-a928-64d81e956788 |   frnds10
 ac5ef240-70b9-4615-9744-b2274a605fc0 | to_delete
 b3400bf5-354d-4768-bc9f-8cb0293be540 |    frnds9
 b3a475b4-67b3-46c2-a7e2-59043217be69 |    frnds8
 be34de28-22aa-4d68-b205-5421fbd5ed66 |   frnds13
 c4f7d039-3328-4ebd-afb8-8b547446ca89 | to_delete
 d14b5ce2-15fe-4879-a131-360b1d6092b6 |   frnds21
 dde13eae-321a-4e02-ab5d-94512ac45986 |    frnds2
 e666ba23-91aa-4f68-84bf-46115b2dd8ac |   frnds23
 f3e506eb-9644-4fd2-bd03-3a6db6cad504 | to_delete
 f7b30860-033a-498e-80e0-a99a794fc7d1 |   frnds22
 fb5aa463-70c3-46b2-825c-fd745165d3a3 |    frnds5
 fc1d289e-3836-44ef-a2cd-9a3047b02740 |    frnds3
 fcce7964-0016-435e-837a-2ebc6416bb89 | to_delete
 feed474e-d7e0-4a36-afae-15735c7afe3f |      alex
```
Then I delete the rows:
```
DELETE FROM story.users WHERE id = ac5ef240-70b9-4615-9744-b2274a605fc0;
DELETE FROM story.users WHERE id = c4f7d039-3328-4ebd-afb8-8b547446ca89;
DELETE FROM story.users WHERE id = f3e506eb-9644-4fd2-bd03-3a6db6cad504;
DELETE FROM story.users WHERE id = fcce7964-0016-435e-837a-2ebc6416bb89;
```
And both filter and search return the same result, as it was expected:
```
 id                                   | username
--------------------------------------+----------
 a2c10b20-d2cb-4eed-9c26-94bdb6eefb2e |  frnds25
 a3996aec-ce15-4bc2-a928-64d81e956788 |  frnds10
 b3400bf5-354d-4768-bc9f-8cb0293be540 |   frnds9
 b3a475b4-67b3-46c2-a7e2-59043217be69 |   frnds8
 be34de28-22aa-4d68-b205-5421fbd5ed66 |  frnds13
 d14b5ce2-15fe-4879-a131-360b1d6092b6 |  frnds21
 dde13eae-321a-4e02-ab5d-94512ac45986 |   frnds2
 e666ba23-91aa-4f68-84bf-46115b2dd8ac |  frnds23
 f7b30860-033a-498e-80e0-a99a794fc7d1 |  frnds22
 fb5aa463-70c3-46b2-825c-fd745165d3a3 |   frnds5
 fc1d289e-3836-44ef-a2cd-9a3047b02740 |   frnds3
 feed474e-d7e0-4a36-afae-15735c7afe3f |     alex
```
Could you please provide more specific info to reproduce the issue?

By the way, are you intentionally adding twice the "sort by id" clause?

**Comment by ayurkows** [comment] 2016-03-22 17:37
I don't have any more specific info to reproduce, sorry. You can close this if you'd like, all is working for us using filter so not going to worry about it.

The query is generated from a request, which is the reason for the sort by id twice. Going to add a check in our script in case that causes any strange behavior.

**Comment by adelapena** [comment] 2016-03-29 18:23
Ok, I'll close it. We can always reopen this issue if the problem reproduces ever.

**Closed by adelapena** 2016-03-29 18:23 UTC
