### ISSUE TITLE
Support for Cassandra 3.11.1?

### ISSUE THREAD

**Issue by hkroger** [Stratio/cassandra-lucene-index#362] opened 2017-10-13 12:14 UTC
Hi,

Do you know when the build against 3.11.1 would be available?

We are using Lucene with latest and due to multiple bugs in 3.11.0 we are desperately waiting for this build so that we can upgrade.

Thanks :)

**Comment by johnyannj** [comment] 2017-10-18 03:12
me too...

**Comment by dxps** [comment] 2017-10-23 14:44
Indeed, we also desperately need 3.11.1!

**Comment by masumsoft** [comment] 2017-10-24 07:56
same here

**Comment by cristd** [comment] 2017-10-24 07:57
We also need the build for 3.11.1, as the lucene index 3.11.0 doesn't seem to be working with C* 3.11.1

**Comment by karankap** [comment] 2017-10-27 08:58
me 2

**Comment by roadrunner** [comment] 2017-10-28 15:09
+1 as well. 
maintainers must be on vacation

**Comment by evildecay** [comment] 2017-10-31 07:49
Temporary solution:

https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.11.0/plugin/src/main/scala/com/stratio/cassandra/lucene/IndexWriterWide.scala#L87
```golang
// if (row.hasLiveData(nowInSec)) {
if (row.hasLiveData(nowInSec, metadata.enforceStrictLiveness())) {
```

https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.11.0/plugin/src/main/scala/com/stratio/cassandra/lucene/IndexWriterSkinny.scala#L71
```golang
// if (row.hasLiveData(nowInSec)) {
if (row.hasLiveData(nowInSec, metadata.enforceStrictLiveness())) {
```

https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.11.0/plugin/src/main/java/org/apache/cassandra/service/LuceneStorageProxy.java#L98
```golang
// result = group.limits().filter(result, group.nowInSec());
result = group.limits().filter(result, group.nowInSec(), false, metadata.enforceStrictLiveness());
```
Thanks @johnyannj

**Comment by roadrunner** [comment] 2017-10-31 09:59
hey @evildecay 
did you force to re-index or just a regular version upgrade?

**Comment by evildecay** [comment] 2017-10-31 10:51
Hi @roadrunner 
I just a regular version upgrade, If it is the production environment, it is best to test and then upgrade.

The parameters are mainly related to materialized view and static.
If you use materialized view and static column that you may need to seriously consider the meaning of the parameters.

**Comment by roadrunner** [comment] 2017-11-01 15:09
hello @evildecay 
I don't use static columns at all.
just materialized views and lucene indexes. 
I will try to checkout the source,  re-compile  and upgrade on dev environment to give it a try

**Comment by hkroger** [comment] 2017-11-02 09:17
@roadrunner, @evildecay:

I created a PR based on your input:
https://github.com/Stratio/cassandra-lucene-index/pull/366

Can you check that?

**Comment by noxvost** [comment] 2017-11-10 14:24
For me this fix doesn't work: searching by clustering columns (match, in) stop working (comparing to 3.10 - I hadn't checked with vanilla 3.11)

**Comment by roadrunner** [comment] 2017-11-10 14:48
same here @evgeny-pasynkov , @hkroger 
i did fallback to 3.10 as well

**Comment by hkroger** [comment] 2017-11-10 15:54
@evgeny-pasynkov, @roadrunner can you give an example of a test case how to reproduce it? I could have a look at it

**Comment by hkroger** [comment] 2017-11-13 20:16
@evgeny-pasynkov, @roadrunner can you give an example of use cases where failed. A schema and index definition would help already.

**Comment by noxvost** [comment] 2017-11-14 13:05
I'm trying to build a minimal reproducible case (since we are using all this stuff through custom DSL, it is not that easy)

**Comment by noxvost** [comment] 2017-11-14 14:53
@hkroger I am unable to reproduce the problem from the scratch (i.e. by pure cqlsh commands). But I have a tiny database where the problem is reproduced. This database is a result of test run, where a small amount of data is added through java api library. I can share this database if you are interested - please contact me privately (evgeny.pasynkov@jetbrains.com)

**Comment by hkroger** [comment] 2017-11-14 15:00
@evgeny-pasynkov I sent you an email.

**Comment by otaviojava** [comment] 2017-11-17 13:35
I tested this PR on Cassandra 3.11.1, and it does not work.

**Comment by hkroger** [comment] 2017-11-17 13:40
@otaviojav what is the the issue you are having?

**Comment by otaviojava** [comment] 2017-11-17 14:44
@hkroger I did a little mistake, I reviewed here and that is working.
Thank you.

**Comment by hkroger** [comment] 2017-11-17 16:58
I did a small change that seems to fix the problem that @evgeny-pasynkov is having. Maybe someone else could test it as well that it doesn't break their setup.

**Comment by noxvost** [comment] 2017-11-20 13:19
Confirm - works for me. Though need to wait for PR being merged to push this to production

**Comment by johnyannj** [comment] 2017-11-22 09:29
I think it is better like this

row.hasLiveData(nowInSec, metadata.enforceStrictLiveness())

beacuse the java doc of  hasLiveData is :

```
@param enforceStrictLiveness whether the row should be purged if there is no PK liveness info,
     *                              normally retrieved from {@link CFMetaData#enforceStrictLiveness()}
```

**Comment by najamsk** [comment] 2017-11-28 08:17
any update?

**Comment by hkroger** [comment] 2017-11-28 08:40
Hi,

I’m away from keyboard for two weeks but I’ll check and test after that the change proposed by @johnyannj

**Comment by najamsk** [comment] 2017-11-28 14:24
ok i am running cassandra 3.11.1 and tried to change result = group.limits().filter(result, group.nowInSec(), true, false);  and tif (row.hasLiveData(nowInSec, metadata.enforceStrictLiveness())) but when try to compile it fails. 

[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (scala-compile-first) @ cassandra-lucene-index-plugin ---
[INFO] /home/najam/work/cassandra-lucene-index/plugin/src/main/java:-1: info: compiling
[INFO] /home/najam/work/cassandra-lucene-index/plugin/src/main/scala:-1: info: compiling
[INFO] Compiling 156 source files to /home/najam/work/cassandra-lucene-index/plugin/target/classes at 1511878733412
[ERROR] /home/najam/work/cassandra-lucene-index/plugin/src/main/scala/com/stratio/cassandra/lucene/IndexWriterSkinny.scala:71: error: too many arguments (2) for method hasLiveData: (x$1: Int)Boolean
[ERROR]         if (row.hasLiveData(nowInSec, false)) {
[ERROR]                                       ^
[ERROR] /home/najam/work/cassandra-lucene-index/plugin/src/main/scala/com/stratio/cassandra/lucene/IndexWriterWide.scala:87: error: too many arguments (2) for method hasLiveData: (x$1: Int)Boolean
[ERROR]       if (row.hasLiveData(nowInSec, false)) {
[ERROR]                                     ^
[ERROR] two errors found
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Cassandra Lucene index ............................. SUCCESS [ 11.455 s]
[INFO] Cassandra Lucene Index builder ..................... SUCCESS [ 56.195 s]
[INFO] Cassandra Lucene Index plugin ...................... FAILURE [01:17 min]
[INFO] Cassandra Lucene Index distribution ................ SKIPPED

**Comment by evildecay** [comment] 2017-11-29 01:49
@najamsk 
    Cassandra lib must be 3.11.1, Please check your porm.xml

**Comment by najamsk** [comment] 2017-11-29 10:21
I did changes suggest on [#366](https://github.com/Stratio/cassandra-lucene-index/pull/366). 
while creating lucene index got error 

Request timed out while waiting for schema agreement. See Session.execute[_async](timeout) and Cluster.max_schema_agreement_wait.

when i tried to create index again it said already created. i checked by querying and it worked. multi node cluster with lucene on each nodes can query indexes.

**Comment by hkroger** [comment] 2017-12-17 21:26
I used the metadata enforceLiveness flag now as suggested by @johnyannj and it works for me.

I pushed the update to PR.

**Comment by ealonsodb** [comment] 2017-12-19 16:31
Hi @hkroger, @johnyannj @najamsk @evgeny-pasynkov: 

We have had some problems and could not upload this for a long time. Thank you for your apportation. I am testing your PR with testsAT. I think i could release this week.

**Comment by hkroger** [comment] 2018-01-03 10:34
Hi @ealonsodb! Any news regarding the release?

**Comment by ealonsodb** [comment] 2018-01-03 11:05
Hi @hkroger 
The release is done [3.11.1.0](https://github.com/Stratio/cassandra-lucene-index/tree/3.11.1.0)

**Closed as completed** 2018-01-03 11:06 UTC
