### ISSUE TITLE
'NoneType' object has no attribute 'sub_types' for query map index

### ISSUE THREAD

**Issue by wanghong230** [Stratio/cassandra-lucene-index#210] opened 2016-10-11 20:46 UTC
Cassandra version: 3.7
Lucene Index version: 3.7.1

```SQL
cqlsh:axdb> CREATE KEYSPACE test
        ...   WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
cqlsh:axdb> use test;
cqlsh:test> CREATE TABLE user_profiles (
        ...    login text PRIMARY KEY,
        ...    first_name text,
        ...    last_name text,
        ...    addresses map<text,text>
        ... );
cqlsh:test> 
cqlsh:test> CREATE CUSTOM INDEX test_index ON test.user_profiles()
        ... USING 'com.stratio.cassandra.lucene.Index'
        ... WITH OPTIONS = {
        ...    'refresh_seconds': '1',
        ...    'schema': '{
        ...       fields: {
        ...          addresses: {type: "string"}
        ...       }
        ...    }'
        ... };
cqlsh:test> INSERT INTO user_profiles (login, first_name, last_name, addresses)
        ...    VALUES('user','Peter','Handsome',
        ...            {'San Francisco':'Market street 2', 'Madrid': 'Calle Velazquez' })
        ... ;
cqlsh:test> 
cqlsh:test> 
cqlsh:test> 
cqlsh:test> 
cqlsh:test> 
cqlsh:test> select * from user_profiles ;

 login | addresses                                                         | first_name | last_name
-------+-------------------------------------------------------------------+------------+-----------
  user | {'Madrid': 'Calle Velazquez', 'San Francisco': 'Market street 2'} |      Peter |  Handsome

(1 rows)
cqlsh:test> SELECT * FROM user_profiles WHERE expr(tweets_index,'{
        ...    filter: {
        ...       type: "match",
        ...       field: "cities$Madrid",
        ...       value: "San Francisco"
        ...    }
        ... }');
InvalidRequest: code=2200 [Invalid query] message="Invalid index expression, index tweets_index not found for test.user_profiles"
cqlsh:test> 
cqlsh:test> 
cqlsh:test> SELECT * FROM user_profiles WHERE expr(test_index,'{
        ...    filter: {
        ...       type: "match",
        ...       field: "cities$Madrid",
        ...       value: "San Francisco"
        ...    }
        ... }');
InvalidRequest: code=2200 [Invalid query] message="No mapper found for field 'cities$Madrid'"
cqlsh:test> 
cqlsh:test> 
cqlsh:test> 
cqlsh:test> 
cqlsh:test> 
cqlsh:test> 
cqlsh:test> SELECT * FROM user_profiles WHERE expr(test_index,'{    filter: {       type: "match",       field: "addresses$Madrid",       value: "San Francisco"    } }');

 login | addresses | first_name | last_name
-------+-----------+------------+-----------

(0 rows)
cqlsh:test> 
cqlsh:test> SELECT * FROM user_profiles WHERE expr(test_index,'{    filter: {       type: "wildcard",       field: "addresses$Madrid",       value: "*Ca*"    } }');

 login | addresses                                                                                          | first_name | last_name
-------+----------------------------------------------------------------------------------------------------+------------+-----------
  user | OrderedMapSerializedKey([(u'Madrid', u'Calle Velazquez'), (u'San Francisco', u'Market street 2')]) |      Peter |  Handsome

(1 rows)
Failed to format value OrderedMapSerializedKey([(u'Madrid', u'Calle Velazquez'), (u'San Francisco', u'Market street 2')]) : 'NoneType' object has no attribute 'sub_types'
cqlsh:test> 
cqlsh:test> 
cqlsh:test> 
cqlsh:test> 
cqlsh:test> SELECT * FROM user_profiles WHERE expr(test_index,'{    filter: {       type: "match",       field: "addresses$Madrid",       value: "San Francisco"    } }');

 login | addresses | first_name | last_name
-------+-----------+------------+-----------

(0 rows)
cqlsh:test> SELECT * FROM user_profiles WHERE expr(test_index,'{    filter: {       type: "match",       field: "addresses$Madrid",       value: "Calle Velazquez"    } }');

 login | addresses                                                                                          | first_name | last_name
-------+----------------------------------------------------------------------------------------------------+------------+-----------
  user | OrderedMapSerializedKey([(u'Madrid', u'Calle Velazquez'), (u'San Francisco', u'Market street 2')]) |      Peter |  Handsome

(1 rows)
Failed to format value OrderedMapSerializedKey([(u'Madrid', u'Calle Velazquez'), (u'San Francisco', u'Market street 2')]) : 'NoneType' object has no attribute 'sub_types'
```

**Comment by adelapena** [comment] 2016-10-12 12:51
I have just fixed documentation mistakes at [PR 211](https://github.com/Stratio/cassandra-lucene-index/pull/211), thanks for reporting.

About the error about cqlsh failing to format collection columns, it seems to be [the same that you already reported three months ago](https://github.com/Stratio/cassandra-lucene-index/issues/167), still without any further feedback about reproduction steps. It looks like it is produced by [CASSANDRA-11534](https://issues.apache.org/jira/browse/CASSANDRA-11534), and it will be fixed as soon as the patch is applied to Apache Cassandra, unless we find some walk around to solve this cqlsh problem from the plugin. 

The good news is that the formatting bug only affects cqlsh, so Cassandra clients should not be affected:
```scala
import com.datastax.driver.core.Cluster
import scala.collection.JavaConversions._

val cluster = Cluster.builder.addContactPoint("localhost").build
val session = cluster.connect

session.execute(
  """CREATE KEYSPACE IF NOT EXISTS test
    | WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor': 1};
    | """.stripMargin)
session.execute("USE test")
session.execute(
  """CREATE TABLE user_profiles (
    | login text PRIMARY KEY,
    | first_name text,
    | last_name text,
    | addresses map<text,text>
    |);""".stripMargin)
session.execute(
  """CREATE CUSTOM INDEX user_profiles_idx ON user_profiles()
    |USING 'com.stratio.cassandra.lucene.Index'
    |WITH OPTIONS = {
    | 'refresh_seconds': '1',
    | 'schema': '{
    |    fields: {
    |       addresses: {type: "string"}
    |    }
    | }'
    |};""".stripMargin)
session.execute(
  """INSERT INTO user_profiles (login, first_name, last_name, addresses)
    |VALUES('jsmith','John','Smith',
    |           {'London':'Camden Road', 'Madrid': 'Buenavista' });""".stripMargin)
Thread.sleep(2000)
session.execute(
  """SELECT * FROM user_profiles WHERE expr(user_profiles_idx, '{
    |  filter: {type: "match", field: "addresses$Madrid", value: "Buenavista"}
    |}');""".stripMargin).foreach(println)

session.close()
cluster.close()
```

**Closed** 2016-10-25 10:56 UTC
